openapi: 3.0.0
info:
  version: 1.0.0
  title: TODO API
  description: API for managing TODOs

servers:
  - url: http://localhost:8087

paths:
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Username:
                  type: string
                Password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /todo:
    get:
      summary: Retrieve all TODOs
      parameters:
        - in: header
          name: apikey
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of TODOs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Add a new TODO
      parameters:
        - in: header
          name: apikey
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  item:
                    type: string
                  completed:
                    type: boolean
        '400':
          description: Bad request

  /todo/{id}:
    get:
      summary: Retrieve a specific TODO by ID
      parameters:
        - in: header
          name: apikey
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    patch:
      summary: Update a TODO by ID
      parameters:
        - in: header
          name: apikey
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  item:
                    type: string
                  completed:
                    type: boolean
        '400':
          description: Bad request
        '404':
          description: Not found
          
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        item:
          type: string
        completed:
          type: boolean

